version: "3.4"

services:
  db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      TZ: "+00:00"
      MYSQL_DATABASE: "classicmodels"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "for-user-test-only"
      MYSQL_ROOT_PASSWORD: "for-root-test-only"
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    environment:
      DB_USER: "user"
      DB_PASS: "for-user-test-only"
      DB_HOST: "db"
      DB_NAME: "classicmodels"
    ports:
      - 8080:8080
    networks:
      - default

volumes:
  db-data:

networks:
  default:
    name: app-network
